export const design_frame =
    [{
        title: 'IconFont',
        src: '/iconfont.svg',
        url: 'https://www.iconfont.cn/',
        fontsize: 12
    }, {
        title: 'OBZHI',
        src: '/obzhi.ico',
        url: 'https://www.obzhi.com/',
        fontsize: 12
    }, {
        title: '米画师',
        src: '/mhs.ico',
        url: 'https://www.mihuashi.com/',
        fontsize: 12
    }, {
        title: 'Wall 壁纸',
        src: '/wall.png',
        url: 'https://wall.alphacoders.com/finding_wallpapers.php',
        fontsize: 12
    }, {
        title: 'wallpapercave',
        src: '/wallpapercave.ico',
        url: 'https://wallpapercave.com/#',
        fontsize: 12
    }, {
        title: 'GameWall',
        src: '/gamewall.ico',
        url: 'https://www.gamewallpapers.com/',
        fontsize: 12
    }, {
        title: 'Pixabay',
        src: '',
        url: 'https://pixabay.com/zh/',
        fontsize: 12
    }, {
        title: 'P站',
        src: '',
        url: 'https://www.acg-pixiv.com/',
        fontsize: 12
    }, {
        title: '渐变grabient',
        src: '/grabient.ico',
        url: 'https://www.grabient.com/',
        fontsize: 11
    }, {
        title: '站酷',
        src: '/zcool.svg',
        url: 'https://www.zcool.com.cn/',
        fontsize: 12
    }, {
        title: 'undraw',
        src: '/undraw.ico',
        url: 'https://undraw.co/',
        fontsize: 12
    }, {
        title: 'igoutu',
        src: '/igoutu.png',
        url: 'https://igoutu.cn/',
        fontsize: 12
    }, {
        title: 'remixicon',
        src: '/remixicon.ico',
        url: 'https://remixicon.com/',
        fontsize: 12
    }, {
        title: 'iconic',
        src: '/iconic.png',
        url: 'https://iconic.app/',
        fontsize: 12
    }, {
        title: 'iconify',
        src: '/iconify.svg',
        url: 'https://icon-sets.iconify.design/',
        fontsize: 12
    }];