export const design_print =
    [{
        title: 'tinkercad三维设计',
        src: '/tinkercad.ico',
        url: 'https://www.tinkercad.com/',
        fontsize: 12
    }, {
        title: 'bambulab',
        src: '/bambu.png',
        url: 'https://wiki.bambulab.com/zh/home',
        fontsize: 12
    }, {
        title: 'matterhackers',
        src: '/matterhackers.png',
        url: 'https://www.matterhackers.com/',
        fontsize: 12
    }, {
        title: 'thingiverse',
        src: '/thingiverse.png',
        url: 'https://www.thingiverse.com/',
        fontsize: 12
    }, {
        title: 'aigei爱给',
        src: '/aigei.ico',
        url: 'https://www.aigei.com/',
        fontsize: 12
    }, {
        title: 'myminifactory',
        src: '/myminifactory.svg',
        url: 'https://www.myminifactory.com/',
        fontsize: 12
    }, {
        title: 'dayin打印啦',
        src: '/dayin.ico',
        url: 'https://www.dayin.la/',
        fontsize: 12
    }, {
        title: '3dwarehouse',
        src: '/3dwarehouse.ico',
        url: 'https://3dwarehouse.sketchup.com/',
        fontsize: 12
    }, {
        title: 'cgtrader',
        src: '/cgtrader.ico',
        url: 'https://www.cgtrader.com/',
        fontsize: 12
    }, {
        title: 'pinshape',
        src: '/pinshape.ico',
        url: 'https://pinshape.com/',
        fontsize: 12
    }, {
        title: 'turbosquid',
        src: '/turbosquid.png',
        url: 'https://www.turbosquid.com/',
        fontsize: 12
    }, {
        title: 'cger',
        src: '/cger.ico',
        url: 'https://www.cger.com/',
        fontsize: 12
    }];