export const fun_game =
    [{
        title: '明日方舟',
        src: '/mingrifangzhou.ico',
        url: 'https://ak.hypergryph.com/#index',
        fontsize: 12
    }, {
        title: '原神官网',
        src: '/ys.ico',
        url: 'https://ys.mihoyo.com/',
        fontsize: 12
    }, {
        title: '剑与远征',
        src: '/jyyz.ico',
        url: 'https://afk-cn.lilith.com/',
        fontsize: 12
    }, {
        title: '星夜小游戏',
        src: '/xingyexiaoyouxi.ico',
        url: 'https://xingye.me/game/index.php',
        fontsize: 12
    }, {
        title: '4399小游戏',
        src: '/4399.ico',
        url: 'https://www.4399.com/',
        fontsize: 12
    }, {
        title: 'taptap',
        src: '/taptap.ico',
        url: 'https://www.taptap.cn/',
        fontsize: 12
    }, {
        title: '在线玩老游戏',
        src: '/zaixianwan.svg',
        url: 'https://zaixianwan.app/',
        fontsize: 12
    }, {
        title: 'steamDB',
        src: '/vector_prefers_schema.svg',
        url: 'https://steamdb.info/',
        fontsize: 12
    }];