export const fun_video =
    [{
        title: '茶杯狐',
        src: '/cupfox.png',
        url: 'https://cupfox.love/',
        fontsize: 12
    }, {
        title: '哔哩哔哩',
        src: '/bilibili2.svg',
        url: 'https://www.bilibili.com/',
        fontsize: 12
    }, {
        title: '电影天堂',
        src: '/dianyingtiantang.ico',
        url: 'https://dytt.dytt8.net/index.htm',
        fontsize: 12
    }, {
        title: '五杀影院',
        src: '/lol5s.ico',
        url: 'https://www.lol5s.net/',
        fontsize: 12
    }, {
        title: '龙部落',
        src: '/longbuluo.ico',
        url: 'https://m.longbulo.com/',
        fontsize: 12
    }, {
        title: '天狼影视',
        src: '/tzlqjx.ico',
        url: 'https://vip.tzlqjx.com/',
        fontsize: 12
    }, {
        title: '樱花动漫',
        src: '/yhdm.ico',
        url: 'https://www.duanxjyzx.com/',
        fontsize: 12
    }, {
        title: '80s电影网',
        src: '/80s.ico',
        url: 'https://www.80sdy.org/',
        fontsize: 12
    }, {
        title: '片库影院',
        src: '/pianku.ico',
        url: 'https://pkvod.com/',
        fontsize: 12
    }, {
        title: '哩嘀哩嘀',
        src: '/lidilidi.ico',
        url: 'https://www.dilidiliw.com/',
        fontsize: 12
    }, {
        title: '4k影视',
        src: '/4kvm.png',
        url: 'https://www.4kvm.site/',
        fontsize: 12
    }, {
        title: 'HDmoli',
        src: '/hdmoli.ico',
        url: 'https://www.hdmoli.pro/',
        fontsize: 12
    }, {
        title: '策驰影院',
        src: '/lyjixiao.ico',
        url: 'http://www.lyjixiao.com/',
        fontsize: 12
    }, {
        title: 'BT影视',
        src: '/btbtl.png',
        url: 'https://www.btbtl.com/',
        fontsize: 12
    }, {
        title: '4K影视',
        src: '/4kvmtv.png',
        url: 'https://www.4kvm.tv/',
        fontsize: 12
    }, {
        title: '6V6V',
        src: '/6v6vnet.png',
        url: 'https://www.6v6v.net/',
        fontsize: 12
    }, {
        title: '4K世界',
        src: '/4Ksj.ico',
        url: 'https://www.4ksj.com/',
        fontsize: 12
    }, {
        title: '飘花电影',
        src: '',
        url: 'https://brcch.com/',
        fontsize: 12
    }, {
        title: '电影港',
        src: '/cnbjpx.ico',
        url: 'https://www.cnbjpx.com/',
        fontsize: 12
    }, {
        title: '蓝光影院',
        src: '/lgyy123.ico',
        url: 'https://www.lgyy123.com/',
        fontsize: 12
    }, {
        title: 'Pixabay',
        src: '/pixabay.png',
        url: 'https://pixabay.com/',
        fontsize: 12
    }, {
        title: '蚂蚁4K',
        src: '/mayi4k.png',
        url: 'https://www.mayi4k.com/',
        fontsize: 12
    }, {
        title: '85电影网',
        src: '',
        url: 'https://85128.net/',
        fontsize: 12
    }, {
        title: '小片网',
        src: '',
        url: 'https://xiaopian.vip/index.html',
        fontsize: 12
    }, {
        title: '迅雷电影天堂',
        src: '/xl720.ico',
        url: 'https://www.xl720.com/',
        fontsize: 12
    }, {
        title: 'SeedHub',
        src: '/seedhub.ico',
        url: 'https://www.seedhub.cc/',
        fontsize: 12
    }, {
        title: '高清MP4',
        src: '/mp4ba.ico',
        url: 'https://www.mp4ba.vip/',
        fontsize: 12
    }];