export const fun_video =
    [{
        title: '茶杯狐',
        src: '/cupfox.png',
        url: 'https://cupfox.love/',
        fontsize: 12
    }, {
        title: '哔哩哔哩',
        src: '/bilibili2.svg',
        url: 'https://www.bilibili.com/',
        fontsize: 12
    }, {
        title: '电影天堂',
        src: '/dianyingtiantang.ico',
        url: 'https://dytt.dytt8.net/index.htm',
        fontsize: 12
    }, {
        title: '五杀影院',
        src: '/lol5s.ico',
        url: 'https://www.lol5s.net/',
        fontsize: 12
    }, {
        title: '龙部落',
        src: '/longbuluo.ico',
        url: 'https://m.longbulo.com/',
        fontsize: 12
    }, {
        title: '天狼影视',
        src: '/tzlqjx.ico',
        url: 'https://vip.tzlqjx.com/',
        fontsize: 12
    }, {
        title: '樱花动漫',
        src: '/yhdm.ico',
        url: 'https://www.duanxjyzx.com/',
        fontsize: 12
    }, {
        title: '80s电影网',
        src: '/80s.ico',
        url: 'https://www.80sdy.org/',
        fontsize: 12
    }, {
        title: '片库影院',
        src: '/pianku.ico',
        url: 'https://pkvod.com/',
        fontsize: 12
    }, {
        title: '哩嘀哩嘀',
        src: '/lidilidi.ico',
        url: 'https://www.dilidiliw.com/',
        fontsize: 12
    }, {
        title: '4k影视',
        src: '/4kvm.png',
        url: 'https://www.4kvm.site/',
        fontsize: 12
    }, {
        title: 'HDmoli',
        src: '/hdmoli.ico',
        url: 'https://www.hdmoli.pro/',
        fontsize: 12
    }];