export const home_common =
    [{
        title: '百度搜索',
        src: '/baidu.svg',
        url: 'https://www.baidu.com/',
        fontsize: 12
    }, {
        title: '百度翻译',
        src: '/fanyi-baidu.svg',
        url: 'https://fanyi.baidu.com/',
        fontsize: 12
    }, {
        title: '',
        src: '/logo-baike.svg',
        url: 'https://baike.baidu.com/',
        fontsize: 12
    }, {
        title: '必应搜索',
        src: '/biying.png',
        url: 'https://cn.bing.com/',
        fontsize: 12
    }, {
        title: '通义千问',
        src: '/tyqw.svg',
        url: 'https://tongyi.aliyun.com/qianwen/',
        fontsize: 12
    }, {
        title: '文心一言',
        src: '/wxyy.png',
        url: 'https://yiyan.baidu.com/',
        fontsize: 12
    }, {
        title: 'KiMi',
        src: '/kimi.ico',
        url: 'https://kimi.moonshot.cn/',
        fontsize: 12
    }, {
        title: 'DeepSeek',
        src: '/deepseek.svg',
        url: 'https://chat.deepseek.com/',
        fontsize: 12
    }, {
        title: '豆包',
        src: '/doubao.png',
        url: 'https://www.doubao.com/chat/',
        fontsize: 12
    }, {
        title: '知乎直答',
        src: '/zhzd.png',
        url: 'https://zhida.zhihu.com/',
        fontsize: 12
    }];