export const home_work =
    [{
        title: 'QQ邮箱',
        src: '/qqmail.png',
        url: 'https://mail.qq.com/',
        fontsize: 12
    }, {
        title: '公司网站',
        src: '/biobank.svg',
        url: 'https://www.origincell.com/',
        fontsize: 12
    }, {
        title: '原能生物',
        src: '/biobank.svg',
        url: 'https://www.bio-bank.com/',
        fontsize: 10
    }, {
        title: '艾尔温',
        src: '/ikelvin.ico',
        url: 'http://ikelvinbio.com/',
        fontsize: 12
    }, {
        title: '基点',
        src: '/genepoint.ico',
        url: 'https://www.genepoint.cn/',
        fontsize: 12
    }, {
        title: '酷复德检测',
        src: '/kufferath.ico',
        url: 'https://www.kufferath-group.com/',
        fontsize: 12
    }, {
        title: 'Gitea',
        src: '/gitea.svg',
        url: 'http://192.168.161.88:3000/',
        fontsize: 12
    }, {
        title: '长风网',
        src: '/cfw.ico',
        url: 'https://trainspace.cfnet.org.cn/I888#/',
        fontsize: 12
    }, {
        title: '开放大学',
        src: '/syxy.png',
        url: 'https://syxy.ouchn.cn/index.html',
        fontsize: 12
    }];