export const home_tool =
    [{
        title: '菜鸟工具',
        src: '/cainiaogongju.png',
        url: 'https://c.runoob.com/',
        fontsize: 12
    }, {
        title: '脚本之家',
        src: '/jiaoben.ico',
        url: 'http://tools.jb51.net/',
        fontsize: 12
    }, {
        title: '文本对比',
        src: '/jq22duibi.ico',
        url: 'https://www.jq22.com/textDifference',
        fontsize: 12
    }, {
        title: '在线工具',
        src: '/toollu.ico',
        url: 'https://tool.lu/',
        fontsize: 12
    }, {
        title: '在线转换',
        src: '/onlineconvert.ico',
        url: 'https://www.online-convert.com/',
        fontsize: 12
    }, {
        title: 'speedpdf',
        src: '/speedpdf.ico',
        url: 'https://speedpdf.cn/zh-cn/',
        fontsize: 12
    }, {
        title: '轻松传',
        src: '/easychuan.png',
        url: 'https://easychuan.cn/',
        fontsize: 12
    }, {
        title: 'photopea',
        src: '/photopea.png',
        url: 'https://www.photopea.com/',
        fontsize: 12
    }, {
        title: 'removebg',
        src: '/remove.ico',
        url: 'https://www.remove.bg/zh',
        fontsize: 12
    }, {
        title: 'iloveimg',
        src: '/iloveimg.png',
        url: 'https://www.iloveimg.com/zh-cn',
        fontsize: 12
    }, {
        title: 'processon脑图',
        src: '/processOn.ico',
        url: 'https://www.processon.com/',
        fontsize: 12
    }, {
        title: '万能兔',
        src: '/wntool.ico',
        url: 'https://www.wntool.com/',
        fontsize: 12
    }];