export const makerdata =
    [{
        title: 'DeviceHive',
        src: '/devicehive.png',
        url: 'https://devicehive.com/',
        fontsize: 12
    }, {
        title: 'ROS',
        src: '/ros.ico',
        url: 'https://www.ros.org/',
        fontsize: 12
    }, {
        title: '树莓派实验室',
        src: '/shumeipai.ico',
        url: 'https://shumeipai.nxez.com/',
        fontsize: 11
    }, {
        title: '树莓派论坛',
        src: '/shumeipailuntan.ico',
        url: 'http://www.shumeipai.net/portal.php',
        fontsize: 12
    }, {
        title: 'Raspberrypi',
        src: '/raspberry.png',
        url: 'https://www.raspberrypi.com/',
        fontsize: 12
    }, {
        title: '微雪电子',
        src: '/wx.ico',
        url: 'https://www.waveshare.net/',
        fontsize: 12
    }, {
        title: 'Lattepanda',
        src: '/lattepanda.ico',
        url: 'https://www.lattepanda.com/',
        fontsize: 12
    }, {
        title: 'Balena',
        src: '/balena.png',
        url: 'https://etcher.balena.io/',
        fontsize: 12
    }, {
        title: '树莓派官网',
        src: '/raspberry.png',
        url: 'https://www.raspberrypi.org/',
        fontsize: 12
    }, {
        title: '趣无尽',
        src: '/quwujin.ico',
        url: 'https://make.quwj.com/',
        fontsize: 12
    }, {
        title: '立创商城',
        src: '/lc.ico',
        url: 'https://www.szlcsc.com/',
        fontsize: 12
    }, {
        title: '嘉立创',
        src: '/jlc.ico',
        url: 'https://www.jlc.com/',
        fontsize: 12
    }, {
        title: '嘉立创开源',
        src: '/oshwhub.ico',
        url: 'https://oshwhub.com/',
        fontsize: 12
    }, {
        title: 'Tensorflow',
        src: '/tensorflow.png',
        url: 'https://tensorflow.google.cn/?hl=zh-cn',
        fontsize: 12
    }, {
        title: 'arduino实验室',
        src: '/arduino.ico',
        url: 'https://arduino.nxez.com/',
        fontsize: 12
    }, {
        title: 'aimrt 机器人框架',
        src: '',
        url: 'https://docs.aimrt.org/index.html',
        fontsize: 12
    }];