export const program_front =
    [{
        title: '',
        src: '/hugo-logo-wide.svg',
        url: 'https://gohugo.io/',
        fontsize: 12
    }, {
        title: 'Tailwind',
        src: '/tailwind.ico',
        url: 'https://tailwind.nodejs.cn/',
        fontsize: 12
    }, {
        title: 'DCloud官网',
        src: '/dcloud.png',
        url: 'https://www.dcloud.io/',
        fontsize: 12
    }, {
        title: 'H5Plus',
        src: '/h5plus.ico',
        url: 'https://www.html5plus.org/doc/zh_cn/accelerometer.html',
        fontsize: 12
    }, {
        title: 'MIUI官网',
        src: '/dcloud.png',
        url: 'https://mui.dcloud.net.cn/',
        fontsize: 12
    }, {
        title: 'UNI-app',
        src: '/dcloud.png',
        url: 'https://uniapp.dcloud.net.cn/',
        fontsize: 12
    }, {
        title: 'DaisyUI',
        src: '/daisyui.png',
        url: 'https://daisyui.com/',
        fontsize: 12
    }, {
        title: 'Element+',
        src: '/elementui.svg',
        url: 'https://element-plus.org/zh-CN/component/overview.html',
        fontsize: 12
    }, {
        title: '图鸟APP',
        src: '/tuniao-logo.svg',
        url: 'https://vue3.tuniaokj.com/',
        fontsize: 12
    }, {
        title: 'DataV大屏',
        src: '/datav.ico',
        url: 'https://datav-vue3.jiaminghi.com/',
        fontsize: 12
    }, {
        title: 'Vue.js官网',
        src: '/vue.svg',
        url: 'https://cn.vuejs.org/',
        fontsize: 12
    }, {
        title: 'vben admin',
        src: '/vben.ico',
        url: 'https://v2.vben.pro/',
        fontsize: 12
    }, {
        title: 'vben admin doc',
        src: '/vben.ico',
        url: 'https://doc.vvbin.cn/',
        fontsize: 11
    }, {
        title: 'primevue',
        src: '/primevue.ico',
        url: 'https://primevue.org/',
        fontsize: 12
    }, {
        title: 'VuePress',
        src: '/vuepress.png',
        url: 'https://v2.vuepress.vuejs.org/zh/',
        fontsize: 12
    }, {
        title: 'Tauri',
        src: '/tauri.png',
        url: 'https://tauri.app/zh-cn/',
        fontsize: 12
    }, {
        title: 'Tauri V2',
        src: '/tauriv2.svg',
        url: 'https://v2.tauri.app/',
        fontsize: 12
    }, {
        title: 'electronjs',
        src: '/electronjs.svg',
        url: 'https://electronjs.p2hp.com/',
        fontsize: 12
    }, {
        title: 'threejs',
        src: '/three.ico',
        url: 'https://threejs.org/',
        fontsize: 12
    }, {
        title: 'Axios',
        src: '/axios.png',
        url: 'http://www.axios-js.com/',
        fontsize: 12
    }, {
        title: 'docsify',
        src: '/docsify.ico',
        url: 'https://docsify.js.org/#/',
        fontsize: 12
    }, {
        title: 'ant_design_vue',
        src: '/antdv.svg',
        url: 'https://2x.antdv.com/components/overview/',
        fontsize: 10
    }, {
        title: 'JQuery 之家',
        src: '/jqueryjia.png',
        url: 'http://www.htmleaf.com/',
        fontsize: 12
    }, {
        title: 'Jquery 插件',
        src: '/jquerychajian.png',
        url: 'https://www.jq22.com/',
        fontsize: 12
    }];