export const program_code =
    [{
        title: 'GitHub',
        src: '/github.svg',
        url: 'https://github.com/',
        fontsize: 12
    }, {
        title: 'Gitee 码云',
        src: '/gitee.svg',
        url: 'https://gitee.com/',
        fontsize: 12
    }, {
        title: '博客园',
        src: '/cnblogs.svg',
        url: 'https://www.cnblogs.com/',
        fontsize: 12
    }, {
        title: 'PUDN',
        src: '/pudn.png',
        url: 'http://www.pudn.com/',
        fontsize: 12
    }, {
        title: 'gitcode',
        src: '/gitcode.png',
        url: 'https://gitcode.com/',
        fontsize: 12
    }, {
        title: '简书',
        src: '/jianshu.svg',
        url: 'http://www.jianshu.com/',
        fontsize: 12
    }, {
        title: '云代码',
        src: '/yundaima.ico',
        url: 'https://yuncode.net/',
        fontsize: 12
    }, {
        title: 'W3C',
        src: '/w3c.ico',
        url: 'https://www.w3cschool.cn/',
        fontsize: 12
    }, {
        title: '异常教程',
        src: '/except.ico',
        url: 'https://www.exception.site/',
        fontsize: 12
    }, {
        title: 'codesandbox',
        src: '/codesandbox.ico',
        url: 'https://codesandbox.io/',
        fontsize: 12
    }, {
        title: 'websim',
        src: '/websim.ico',
        url: 'https://websim.ai/',
        fontsize: 12
    }, {
        title: '云代码',
        src: '/yundaima.ico',
        url: 'https://yuncode.net/',
        fontsize: 12
    }];